version: "3.6"

services:
  jamato:
    build: "./app"
    ports:
      - "8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www
    ports:
      - "${APP_HTTP_PORT}:80"
    depends_on:
      - "jamato"